export const tariPasswordMessages = {
  en: { changePassword: 'Change password', currentPassword: 'Current password', newPassword: 'New password', passwordChanged: 'Password changed and backup exported', changePasswordNotice: 'Enter your current password and download a new encrypted backup. Old backup files still work with their old password.' },
  de: { changePassword: 'Passwort ändern', currentPassword: 'Aktuelles Passwort', newPassword: 'Neues Passwort', passwordChanged: 'Passwort geändert und Backup exportiert', changePasswordNotice: 'Gib dein aktuelles Passwort ein und lade ein neues verschlüsseltes Backup herunter. Alte Backups funktionieren weiterhin mit ihrem alten Passwort.' },
  es: { changePassword: 'Cambiar contraseña', currentPassword: 'Contraseña actual', newPassword: 'Nueva contraseña', passwordChanged: 'Contraseña cambiada y copia exportada', changePasswordNotice: 'Introduce tu contraseña actual y descarga una nueva copia cifrada. Las copias antiguas siguen funcionando con su contraseña anterior.' },
  ru: { changePassword: 'Изменить пароль', currentPassword: 'Текущий пароль', newPassword: 'Новый пароль', passwordChanged: 'Пароль изменён, резервная копия экспортирована', changePasswordNotice: 'Введите текущий пароль и скачайте новую зашифрованную резервную копию. Старые файлы по-прежнему работают со старым паролем.' },
  zh: { changePassword: '更改密码', currentPassword: '当前密码', newPassword: '新密码', passwordChanged: '密码已更改，备份已导出', changePasswordNotice: '输入当前密码并下载新的加密备份。旧备份文件仍可使用旧密码恢复。' },
  hi: { changePassword: 'पासवर्ड बदलें', currentPassword: 'वर्तमान पासवर्ड', newPassword: 'नया पासवर्ड', passwordChanged: 'पासवर्ड बदला और बैकअप निर्यात किया गया', changePasswordNotice: 'वर्तमान पासवर्ड दर्ज करें और नया एन्क्रिप्टेड बैकअप डाउनलोड करें। पुराने बैकअप अपने पुराने पासवर्ड से काम करते रहेंगे।' },
  bn: { changePassword: 'পাসওয়ার্ড পরিবর্তন করুন', currentPassword: 'বর্তমান পাসওয়ার্ড', newPassword: 'নতুন পাসওয়ার্ড', passwordChanged: 'পাসওয়ার্ড পরিবর্তিত এবং ব্যাকআপ রপ্তানি হয়েছে', changePasswordNotice: 'বর্তমান পাসওয়ার্ড দিন এবং নতুন এনক্রিপ্ট করা ব্যাকআপ ডাউনলোড করুন। পুরোনো ব্যাকআপ তাদের পুরোনো পাসওয়ার্ড দিয়ে কাজ করবে।' }
}
