export const walletFeedbackMessages = {
  en: { account: 'Account', unknown: 'Balance has not loaded yet.', unavailable: 'Prices are unavailable. Token balances are shown below.', partial: 'Some prices are unavailable. Priced assets total {{amount}}.', refreshing: 'Refreshing balances. Showing the previous balance.', amountInvalid: 'Enter an amount greater than zero.', amountBalance: 'Amount exceeds your available balance.', amountFee: 'Leave enough native currency for the network fee.', recipientRequired: 'Enter a recipient address.', recipientInvalid: 'Enter a valid EVM address.', available: 'Available: {{amount}} {{symbol}}' },
  de: { account: 'Konto', unknown: 'Der Kontostand wurde noch nicht geladen.', unavailable: 'Preise sind nicht verfügbar. Token-Bestände stehen unten.', partial: 'Einige Preise fehlen. Bewertete Vermögenswerte: {{amount}}.', refreshing: 'Bestände werden aktualisiert. Der vorherige Stand wird angezeigt.', amountInvalid: 'Gib einen Betrag größer als null ein.', amountBalance: 'Der Betrag übersteigt dein verfügbares Guthaben.', amountFee: 'Lass genug native Währung für die Netzwerkgebühr übrig.', recipientRequired: 'Gib eine Empfängeradresse ein.', recipientInvalid: 'Gib eine gültige EVM-Adresse ein.', available: 'Verfügbar: {{amount}} {{symbol}}' },
  es: { account: 'Cuenta', unknown: 'El saldo aún no se ha cargado.', unavailable: 'Precios no disponibles. Los saldos aparecen abajo.', partial: 'Faltan algunos precios. Activos valorados: {{amount}}.', refreshing: 'Actualizando saldos. Se muestra el saldo anterior.', amountInvalid: 'Introduce un importe mayor que cero.', amountBalance: 'El importe supera tu saldo disponible.', amountFee: 'Deja suficiente moneda nativa para la comisión de red.', recipientRequired: 'Introduce una dirección de destinatario.', recipientInvalid: 'Introduce una dirección EVM válida.', available: 'Disponible: {{amount}} {{symbol}}' },
  ru: { account: 'Аккаунт', unknown: 'Баланс ещё не загружен.', unavailable: 'Цены недоступны. Балансы токенов показаны ниже.', partial: 'Некоторые цены недоступны. Активы с известной ценой: {{amount}}.', refreshing: 'Обновление балансов. Показан предыдущий баланс.', amountInvalid: 'Введите сумму больше нуля.', amountBalance: 'Сумма превышает доступный баланс.', amountFee: 'Оставьте нативную валюту для комиссии сети.', recipientRequired: 'Введите адрес получателя.', recipientInvalid: 'Введите корректный EVM-адрес.', available: 'Доступно: {{amount}} {{symbol}}' },
  zh: { account: '账户', unknown: '余额尚未加载。', unavailable: '价格不可用。代币余额显示在下方。', partial: '部分价格不可用。已定价资产合计 {{amount}}。', refreshing: '正在刷新余额，显示上次余额。', amountInvalid: '请输入大于零的金额。', amountBalance: '金额超过可用余额。', amountFee: '请留足原生币支付网络费。', recipientRequired: '请输入收款地址。', recipientInvalid: '请输入有效的 EVM 地址。', available: '可用：{{amount}} {{symbol}}' },
  hi: { account: 'खाता', unknown: 'शेष अभी लोड नहीं हुआ है।', unavailable: 'कीमतें उपलब्ध नहीं हैं। टोकन शेष नीचे दिखाए गए हैं।', partial: 'कुछ कीमतें उपलब्ध नहीं हैं। मूल्य ज्ञात संपत्तियाँ: {{amount}}।', refreshing: 'शेष अपडेट हो रहा है। पिछला शेष दिखाया गया है।', amountInvalid: 'शून्य से अधिक राशि दर्ज करें।', amountBalance: 'राशि उपलब्ध शेष से अधिक है।', amountFee: 'नेटवर्क शुल्क के लिए पर्याप्त मूल मुद्रा छोड़ें।', recipientRequired: 'प्राप्तकर्ता का पता दर्ज करें।', recipientInvalid: 'मान्य EVM पता दर्ज करें।', available: 'उपलब्ध: {{amount}} {{symbol}}' },
  bn: { account: 'অ্যাকাউন্ট', unknown: 'ব্যালেন্স এখনও লোড হয়নি।', unavailable: 'দাম অনুপলব্ধ। টোকেন ব্যালেন্স নিচে দেখানো হয়েছে।', partial: 'কিছু দাম অনুপলব্ধ। জানা দামের সম্পদের মোট {{amount}}।', refreshing: 'ব্যালেন্স আপডেট হচ্ছে। আগের ব্যালেন্স দেখানো হচ্ছে।', amountInvalid: 'শূন্যের চেয়ে বেশি পরিমাণ লিখুন।', amountBalance: 'পরিমাণ উপলব্ধ ব্যালেন্সের বেশি।', amountFee: 'নেটওয়ার্ক ফি দিতে যথেষ্ট নেটিভ মুদ্রা রাখুন।', recipientRequired: 'প্রাপকের ঠিকানা লিখুন।', recipientInvalid: 'বৈধ EVM ঠিকানা লিখুন।', available: 'উপলব্ধ: {{amount}} {{symbol}}' }
}

const reviewMore = {
  en: 'Scroll to review the remaining warnings and acknowledgement.',
  de: 'Scrolle, um die übrigen Warnungen und die Bestätigung zu prüfen.',
  es: 'Desplázate para revisar las advertencias restantes y la confirmación.',
  ru: 'Прокрутите, чтобы прочитать остальные предупреждения и подтверждение.',
  zh: '请滚动查看其余警告和确认选项。',
  hi: 'शेष चेतावनियाँ और पुष्टि देखने के लिए स्क्रॉल करें।',
  bn: 'বাকি সতর্কতা ও সম্মতি দেখতে স্ক্রল করুন।'
}
for (const [locale, message] of Object.entries(reviewMore)) walletFeedbackMessages[locale].reviewMore = message
